### ISSUE TITLE
MD5 verification fails

### ISSUE THREAD

**Issue by rmetzger** [Cascading/vagrant-cascading-hadoop-cluster#11]
Hi,

I don't understand whats going on there.
I got the error twice (I was doing a `vagrant destory` in between) and I assume that the md5 hashes at apache are correct.

```
....

==> hadoop1: err: /Stage[main]/Hadoop/Exec[verify_tarball]/returns: change from notrun to 0 failed: /tmp/verifier /vagrant/hadoop-2.5.2.tar.gz.mds returned 1 instead of one of [0] at /tmp/vagrant-puppet-1/modules-0/hadoop/manifests/init.pp:66
....
==> hadoop1: notice: Finished catalog run in 88.13 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by fs111** [comment]
The checksum file on the mirrors is wrong. It contains the checksums of the RC-1, not the release. See for instance here:
curl http://mirror.23media.de/apache/hadoop/core/hadoop-2.5.2/hadoop-2.5.2.tar.gz.mds

I have disabled the checksum verification for now and opened a JIRA upstream: https://issues.apache.org/jira/browse/HADOOP-11340

FWIW https://issues.apache.org/jira/browse/HADOOP-9928 would be great to have, instead of this mds file stuff, but that is hadoop for you...

**Comment by rmetzger** [comment]
Thank you for fixing this so fast!

**Comment by fs111** [comment]
I had to, my cluster also failed :grin:
