### ISSUE TITLE
Path to Hadoop not being set

### ISSUE THREAD

**Issue by ghost** [Cascading/vagrant-cascading-hadoop-cluster#8]
Hi,
After installation using the "vagrant up" command, I did a ssh into the master (vagrant ssh master) tried to issue
_sudo prepare-cluster.sh_

I get the error 
_sudo: prepare-cluster.sh: command not found_

How do I make this work ?

I did try to manually run the hdfs namenode -format command but get 

_/bin/java: No such file or directory6-openjdk-amd64_

**Comment by fs111** [comment]
Sounds like something went wrong during provisioning. If you still have the output of vagrant up until you logged in, please paste it here. 

Otherwise, please try `vagrant provision` again.

One more question: Where in the world are you located? We try to download hadoop from a nearby mirror, but if there is none, we download from the US, which may time out.

EDIT: Also, which vagrant and VBox version are you using and what is your host OS?

**Comment by ghost** [comment]
I am located in India. I an sorry I don't have the output of vagrant but I am trying again and will see if it resolves the issue and let you know.

I am using Vagrant 1.5.4 and VirtualBox 4.3 on Windows 8.1

Thanks.

**Comment by sidorovis** [comment]
Probably it is version of virtualbox. Or your clone took the sources in windows format \r. So when several scripts try to start sh script with !#/bin/bash it fails because of that symbol.
1) make sure that your virtualbox dont show any mistake while it start vm.
2) check cloned sh scripts

**Comment by ghost** [comment]
Hi sidorovis, you were right ...i had used `git clone` and  it got things messy i guess. I downloaded the zip from github and executed it ...everything went fine ...

Thanks you fs111 and sidorovis ...

**Comment by fs111** [comment]
Glad to hear that it works now. I am going to add the solution to the troubleshooting section of the README.
